force-app/main/default/objects/lwc_Calculator_History__c/lwc_Calculator_History__c.object-meta.xml
<CustomObject>
    <description>Object holding the history for the LWC calculator</description>
    <label>LWC Calculator History</label>
    <nameField>
        <displayFormat>HIS-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LWC Calculator History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/lwc_Calculator_History__c/fields/Number_A__c.field-meta.xml
<CustomField>
    <fullName>Number_A__c</fullName>
    <description>The first number of the calculator</description>
    <label>Number A</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/lwc_Calculator_History__c/fields/Number_B__c.field-meta.xml
<CustomField>
    <fullName>Number_B__c</fullName>
    <description>The second number in the LWC calculator</description>
    <label>Number B</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/lwc_Calculator_History__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADD</fullName>
                <default>true</default>
                <label>ADD</label>
            </value>
            <value>
                <fullName>SUBTRACT</fullName>
            </value>
            <value>
                <fullName>MULTIPLY</fullName>
            </value>
            <value>
                <fullName>DEVIDE</fullName>
            </value>
            <value>
                <fullName>MODULUS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/lwc_Calculator_History__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <description>The result of the calculation</description>
    <label>Result</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/lwc_CalculationHistory.cls
public with sharing class lwc_CalculationHistory {
	
	// List for holding the calculator history records
	public static lwc_Calculator_History__c[] calculatorHistoryRecords = new lwc_Calculator_History__c[]{};


	/**
	 * Method for adding a calculation history record to the list
	 */
	public static void addHistoryRecord(Decimal a, Decimal b, String operator, Decimal result){
		
		// Check if the user has read and create access on the history object
		if(Schema.sObjectType.lwc_Calculator_History__c.isAccessible() && Schema.sObjectType.lwc_Calculator_History__c.isCreateable()){
			
			// Create a new history record
			calculatorHistoryRecords.add(
				new lwc_Calculator_History__c(
					Number_A__c = a,
					Number_B__c = b,
					Operator__c = operator,
					Result__c	= result
				)
			);
		}else{
			throw new lwc_Exception(lwc_Constant.CALC_HIS_NO_RC_MESSAGE);
		}
	}


	/**
	 *	Method to insert the calculation history records
	 */
	public static void saveHistoryRecords(){
		database.insert(calculatorHistoryRecords,false);
	}


	/**
	 *	Method to get the current user's calculation history
	 */
	@AuraEnabled
	public static lwc_Calculator_History__c[] getCalulationHistoryList(){
		
		// Check if the current user can access the lwc_Calculator_History__c object
		if(Schema.sObjectType.lwc_Calculator_History__c.isAccessible()){
			
			// Return the last 10 history records for the current user
			return [
				SELECT 
					CreatedDate, Number_A__c, Number_B__c, Operator__c, Result__c
				FROM 
						lwc_Calculator_History__c 
				WHERE 
					CreatedById = :UserInfo.getUserId()
				ORDER BY 
					CreatedDate DESC 
				LIMIT 10
			];
		}else{
			throw new lwc_Exception(lwc_Constant.CALC_HIS_NO_R_MESSAGE);
		}
	}

}