force-app/main/default/objects/lwc_Calculator_History__c/lwc_Calculator_History__c.object-meta.xml
<CustomObject>
    <description>Object holding the history for the LWC calculator</description>
    <label>LWC Calculator History</label>
    <nameField>
        <displayFormat>HIS-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LWC Calculator History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/lwc_Calculator_History__c/fields/Number_A__c.field-meta.xml
<CustomField>
    <fullName>Number_A__c</fullName>
    <description>The first number of the calculator</description>
    <label>Number A</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/lwc_Calculator_History__c/fields/Number_B__c.field-meta.xml
<CustomField>
    <fullName>Number_B__c</fullName>
    <description>The second number in the LWC calculator</description>
    <label>Number B</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/lwc_Calculator_History__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADD</fullName>
                <default>true</default>
                <label>ADD</label>
            </value>
            <value>
                <fullName>SUBTRACT</fullName>
            </value>
            <value>
                <fullName>MULTIPLY</fullName>
            </value>
            <value>
                <fullName>DEVIDE</fullName>
            </value>
            <value>
                <fullName>MODULUS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/lwc_CalculatorTestBad.cls
/**
 * @author		:	Justus van den Berg
 * @date		:	2020-05-21
 * @description	:	This class is really bad and only tests coverage
 */
@IsTest
public with sharing class lwc_CalculatorTestBad {
	
	/**
	 * Single test method to illustrate how 100% coverage can be achieved
	 * but nothing is acutally tested
	 */
	private static testMethod void getCalculatorCoverage(){

		// "Test" calculation happy paths
		lwc_Calculator.excuteCalculation(1,1,lwc_Calculator.Operator.ADD, true);
		lwc_Calculator.excuteCalculation(1,1,lwc_Calculator.Operator.SUBTRACT, true);
		lwc_Calculator.excuteCalculation(1,1,lwc_Calculator.Operator.MULTIPLY, true);
		lwc_Calculator.excuteCalculation(1,1,lwc_Calculator.Operator.DEVIDE, true);
		lwc_Calculator.excuteCalculation(1,1,lwc_Calculator.Operator.MODULUS, true);

		// "Test the exceptions"
		try{lwc_Calculator.excuteCalculation(1,1,null,true);}catch(Exception e){System.debug('Do nothing');}
		try{lwc_Calculator.excuteCalculation(1,0,lwc_Calculator.Operator.DEVIDE,true);}catch(Exception e){System.debug('Do nothing');}

		// Lwc method
		lwc_Calculator.excuteCalculationFromLwc(1,1,'ADD');
	}
	
	 /**
	 * Single test method to illustrate how 100% coverage can be achieved
	 * but nothing is acutally tested
	 */
	private static testMethod void getCalculationHistoryCoverage(){
		// Test that we have some data
		lwc_CalculationHistory.addHistoryRecord(1, 2, 'ADD', 3);
		lwc_CalculationHistory.saveHistoryRecords();
		lwc_CalculationHistory.getCalulationHistoryList();
	}
	

	/**
	 * 	Method to get some test coverage for the lwc_Calculator_History__c trigger to get code coverage
	 */
	private static testMethod void getCoverageForTriggers(){
		try{insert new lwc_Calculator_History__c(Number_A__c = 1, Number_B__c=2,Operator__c='ADD');		}catch(Exception e){System.debug('Do nothing');}
		try{insert new lwc_Calculator_History__c(Number_A__c = 1, Number_B__c=2,Operator__c='SUBTRACT');}catch(Exception e){System.debug('Do nothing');}
		try{insert new lwc_Calculator_History__c(Number_A__c = 1, Number_B__c=2,Operator__c='MULTIPLY');}catch(Exception e){System.debug('Do nothing');}
		try{insert new lwc_Calculator_History__c(Number_A__c = 1, Number_B__c=2,Operator__c='DEVIDE');	}catch(Exception e){System.debug('Do nothing');}
		try{insert new lwc_Calculator_History__c(Number_A__c = 1, Number_B__c=0,Operator__c='DEVIDE');	}catch(Exception e){System.debug('Do nothing');}
		try{insert new lwc_Calculator_History__c(Number_A__c = 1, Number_B__c=5,Operator__c='MODULUS');	}catch(Exception e){System.debug('Do nothing');}
		try{insert new lwc_Calculator_History__c(Number_A__c = 1, Number_B__c=5,Operator__c='INVALID');	}catch(Exception e){System.debug('Do nothing');}
	}
}